---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      azure_key_vault:
        type: azurekeyvault
        subscription_id: "${AZURE_SUBSCRIPTION_ID}"
        fetch_all_versions: true

    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GITGUARDIAN_API_KEY}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true
    # Job to be able to sync/write secrets from GitGuardian into you vault
    sync:
      # Set to `false` to disable the job
      enabled: true
      # Run every minute
      schedule: '* * * * *'

envFrom:
- secretRef:
    name: gitguardian-nhi-scout-secrets
