---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "nhi-scout.fullname" . }}
  labels:
    {{- include "nhi-scout.labels" . | nindent 4 }}
spec:
  schedule: {{ toJson .Values.inventory.schedule  }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations: {{- toJson . }}
          {{- end }}
          labels:
            {{- include "nhi-scout.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              securityContext: {{ toJson .Values.securityContext }}
              image: "{{ .Values.image.repository }}:{{ .Values.inventory.version }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- if ne .Values.inventory.config.gitguardian nil }}
                - fetch-and-send
                {{- else }}
                - fetch
                {{- end }}
              resources: {{ toJson .Values.resources }}
              envFrom: {{ toJson .Values.envFrom }}
              env:
                - name: INVENTORY_CONFIG_PATH
                  value: /etc/inventory/config.yml
              {{- if .Values.inventory.log_level }}
                - name: RUST_LOG
                  value: {{ .Values.inventory.log_level }}
              {{- end}}
              {{- range .Values.env }}
                - {{ toJson . }}
              {{- end }}
              volumeMounts:
                - name: config
                  mountPath: /etc/inventory
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets: {{ toJson . }}
          {{- end }}
          serviceAccountName: {{ include "nhi-scout.serviceAccountName" . }}
          securityContext: {{ toJson .Values.podSecurityContext }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toJson . }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{ toJson . }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toJson . }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}

          volumes:
            - name: config
              configMap:
                # Provide the name of the ConfigMap containing the files you want
                # to add to the container
                name: {{ include "nhi-scout.fullname" . }}
