{{- if and (ne .Values.inventory.config.gitguardian nil) (.Values.inventory.jobs.sync.enabled) }}
{{ include "nhi-scout.cronjob" (merge (dict "cronjob_name" "sync" "command" "sync-secrets" "schedule" .Values.inventory.jobs.sync.schedule "backOffLimit" .Values.inventory.jobs.sync.backOffLimit "ttlSecondsAfterFinished" .Values.inventory.jobs.sync.ttlSecondsAfterFinished) .) -}}
{{- end }}
