---
apiVersion: v1
kind: Secret
metadata:
  name: gitguardian-nhi-scout-secrets
stringData:
  GITGUARDIAN_API_KEY: "your_gitguardian_token"

  AKEYLESS_ACCESS_ID: "your_akeyless_access_id"
  AKEYLESS_ACCESS_KEY: "your_akeyless_access_key"
