---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      akeyless:
        api_url: https://api.akeyless.io/ # If you use a gateway, change this url to the Gateway API address => `https://my-akeyless-gw.com/api/v2/`
        type: akeyless
        fetch_all_versions: true
        auth_mode: "apikey" # We only support apikey auth mode for the moment
        accessibility: "regular" # Can be `regular` or `personal`
        access_id: "${AKEYLESS_ACCESS_ID}"
        access_key: "${AKEYLESS_ACCESS_KEY}"

    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GITGUARDIAN_API_KEY}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true
    # Job to be able to sync/write secrets from GitGuardian into you vault
    sync:
      # Set to `false` to disable the job
      enabled: true
      # Run every minute
      schedule: '* * * * *'

envFrom:
- secretRef:
    name: gitguardian-nhi-scout-secrets
