---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      gcp:
        type: gcpsecretmanager
        fetch_all_versions: false # Fetch all versions of secrets or not
        service_account_key_file: /path/to/key.json # Replace with actual key file path
        projects: # List of GCP projects or null
        - project-id-1
        - project-id-2
    # To upload, set the gitguardian URL and tokens. Ensure the endpoint path ends with /v1
    # This is optional: omit this to prevent uploading and to only test collection.
    gitguardian:
      endpoint: "https://my-gg-instance/v1"
      api_token: "${GITGUARDIAN_API_KEY}"
  jobs:
    # Job to fetch defined sources
    fetch:
      # Set to `false` to disable the job
      enabled: true
      # Run every 15 minutes
      schedule: '*/15 * * * *'
      send: true
    # Job to be able to sync/write secrets from GitGuardian into you vault
    sync:
      # Set to `false` to disable the job
      enabled: true
      # Run every minute
      schedule: '* * * * *'

envFrom:
- secretRef:
    name: gitguardian-nhi-scout-secrets
