---
# yaml-language-server: $schema=../../values.schema.json

inventory:
  config:
    sources:
      vault-secrets:
        type: hashicorpvault
        vault_address: "https://your-vault-address-here"
        # Token configuration can be read from environment variables like so:
        auth_token: "${HASHICORP_VAULT_TOKEN}"
        fetch_all_versions: true
        path: "secret/"

  jobs:
    fetch:
      schedule: "* * * * *"
      enabled: true
      # send is set to `false` so this job will only retrieve secrets and write there into `${OUTPUT_PATH}`
      send: false

# This needs to be created separately, and contain the following keys:
# - `OUTPUT_PATH` - path that the Scout `fetch` command is using to write the inventory
envFrom:
- secretRef:
    name: gitguardian-nhi-scout-secrets

volumes:
- name: test-local
  hostPath:
      # The host local volume where the inventory will be sent
    path: /tmp/output
    type: DirectoryOrCreate

volumeMounts:
  # The mount point where the inventory will be written. Must be the same directory than the one set in OUTPUT_PATH
- mountPath: /tmp/output
  name: test-local
